### ISSUE TITLE
nested loops with repeat_for cause exceptions

### ISSUE THREAD

**Issue by LukeDRussell** [ansible-network/network-engine#139]
# ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```
ansible --version
ansible 2.6.3
  config file = /Users/4032956/Documents/network-automation/ansible.cfg
  configured module search path = ['/Users/4032956/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/4032956/.pyenv/versions/3.6.6/envs/network-automation/lib/python3.6/site-packages/ansible
  executable location = /Users/4032956/.pyenv/versions/network-automation/bin/ansible
  python version = 3.6.6 (default, Jul 30 2018, 09:47:46) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
ansible-galaxy list | grep ansible.network
v2.6.3
Running a submodule currently on commit 654729f3931d6d9f6485a2a0458753752905e01b

```

# Network OS

- Cisco IOS
- Not applicable

# SUMMARY

When using the template argument `repeat_for` and `repeat_var` I was getting python exceptions.  With help from a developer here he got me to change json_template.py and it started working. I'm not sure really what is happening with the code.

# STEPS TO REPRODUCE

See [this gist](https://gist.github.com/blanchg/4afa62e0fccb3d55111b0f7376ba0416) or [my fork](https://github.com/LukeRussell/cisco_ios/blob/devel/tests/test.yml) of cisco_ios

# EXPECTED RESULTS

[gist](https://gist.github.com/LukeRussell/db8045cb27cd07298b8ad15fdc5fa063#file-with-json_template-fixed)

# ACTUAL RESULTS

Complete [gist](https://gist.github.com/LukeRussell/db8045cb27cd07298b8ad15fdc5fa063#file-with-json_template-as-is)

```
Traceback (most recent call last):
  File "/Users/4032956/.pyenv/versions/3.6.6/envs/network-automation/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 139, in run
    res = self._execute()
  File "/Users/4032956/.pyenv/versions/3.6.6/envs/network-automation/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 577, in _execute
    result = self._handler.run(task_vars=variables)
  File "/Users/4032956/Documents/network-automation/roles/ansible-network.network-engine/action_plugins/command_parser.py", line 159, in run
    resp = self._process_directive(task)
  File "/Users/4032956/Documents/network-automation/roles/ansible-network.network-engine/action_plugins/command_parser.py", line 395, in _process_directive
    return meth(**args)
  File "/Users/4032956/Documents/network-automation/roles/ansible-network.network-engine/action_plugins/command_parser.py", line 413, in do_json_template
    return self.template.run(template, self.ds)
  File "/Users/4032956/Documents/network-automation/roles/ansible-network.network-engine/action_plugins/../lib/network_engine/plugins/template/json_template.py", line 71, in run
    val = self.run(items, variables)
  File "/Users/4032956/Documents/network-automation/roles/ansible-network.network-engine/action_plugins/../lib/network_engine/plugins/template/json_template.py", line 56, in run
    templated_value.append(self.run(items, variables))
  File "/Users/4032956/Documents/network-automation/roles/ansible-network.network-engine/action_plugins/../lib/network_engine/plugins/template/json_template.py", line 24, in run
    key = self.template(item['key'], variables)
TypeError: string indices must be integers
fatal: [localhost]: FAILED! => {}

MSG:

Unexpected failure during module execution.
	to retry, use: --limit @/Users/4032956/Documents/network-automation/retry/test.retry
```

**Comment by trishnaguha** [comment]
@LukeRussell can you please share the exception?

**Comment by LukeDRussell** [comment]
@trishnaguha I've updated the original Issue with actual results and working results with json_template.py fixed (IMO).

**Comment by LukeDRussell** [comment]
Thanks @trishnaguha, works as expected now.
